import type { UiText } from "../components/index.js";

/** UI copy only. Synthetic response bodies and upstream diagnostics are intentionally not translated. */
export const chineseUi = {
  "Settings": "设置", "Settings categories": "设置分类", "General": "通用", "Providers": "供应商", "Plugins": "插件", "Back to providers": "返回供应商",
  "Search models": "搜索模型", "No matching models": "没有匹配的模型", "Manage providers": "管理供应商", "API key": "API 密钥", "Configured": "已配置", "Not configured": "未配置",
  "Add from disk": "从磁盘添加",
  "Remove forgets the path. Files on disk stay.": "移除只会忘掉路径。磁盘上的文件仍在。",
  "Enable is the next idle Trusted apply. A running runtime does not change until then.": "启用表示下一次空闲受信应用。活 runtime 在此之前不变。",
  "Enabled": "已启用",
  "No plugins in this inventory.": "清单里还没有插件。", "Loading plugins…": "正在加载插件…", "Adding plugin…": "正在添加插件…",
  "That plugin is no longer in the inventory.": "该插件已不在清单中。",
  "This plugin is already in the inventory.": "该插件已在清单中。",
  "That file cannot be added as a pi extension.": "该文件不能作为 pi 扩展添加。",
  "The plugin inventory file is damaged or too large and was left unchanged.": "插件清单文件已损坏或过大，未改写。",
  "The plugin inventory is full.": "插件清单已满。",
  "The plugin inventory would exceed its size limit.": "插件清单将超出大小上限。",
  "The plugin inventory could not be saved.": "无法保存插件清单。",
  "Replay Pi logo animation": "重播 Pi 标志动画",
  "Custom extension tool. This approval covers this call only; extension-internal execution is outside this approval and built-in file safeguards.": "自定义扩展工具：本次审批仅覆盖此调用；扩展内部执行不在该审批及内置文件保护范围内。",
  "Set up this project": "设置此项目",
  "Use this project's pi settings and resources?": "是否使用此项目的 pi 设置和资源？",
  "What does this choice affect?": "此选择会影响什么？",
  "A project session needs an explicit resource choice before it can start.": "开始项目会话前需要先作出明确的资源选择。",
  "Cancel keeps this draft and does not grant consent or start a runtime.": "取消会保留这份草稿，不会授予同意，也不会启动 runtime。",
  "Pi chat": "Pi 聊天",
  "Connecting to the extension host…": "正在连接扩展宿主…",
  "Reload the VS Code window to restart controlled execution. Unsent drafts are not persisted; copy them before reloading.": "重新加载 VS Code 窗口可重启受控执行。未发送草稿不会持久保存，请在重载前复制。",
  "No configured model is available. Open Interface settings to configure a provider API key.": "没有可用的已配置模型。请打开界面设置配置供应商 API 密钥。",
  "Open provider settings": "打开供应商设置",
  "(Link blocked — only absolute HTTP(S) links without credentials are allowed.)": "（链接已阻止，仅允许不含凭据的 HTTP(S) 绝对链接。）",
  "Opening an external link through VS Code.": "正在通过 VS Code 打开外部链接。",
  "Task failed": "任务失败",
  "Retrying…": "正在重试…",
  "Compacting context…": "正在压缩上下文…",
  "Task completed": "任务已完成",
  "Task stopped · Side effects are not rolled back.": "任务已停止 · 已有副作用不会回滚。",
  "Preview controls": "预览控制",
  "Simulate pending approvals": "模拟待审批操作",
  "Simulate captured changes": "模拟已捕获修改",
  "Simulate review loss": "模拟审阅丢失",
  "Simulate extension request": "模拟扩展请求",
  "Simulate runtime recovery": "模拟运行恢复",
  "Review changes ({count})": "审阅修改（{count}）",
  "Review changes pages": "修改审阅分页",
  "Review text retained: {bytes} / 8 MiB.": "保留的审阅文本：{bytes} / 8 MiB。",
  "Review data is stale; the runtime or source changed. Refresh the review before relying on it.": "运行时或源码已变化，审阅数据过期，请先刷新。",
  "Review data is unavailable; no captured diff can be opened for missing entries.": "审阅数据不可用，无法打开缺失项的捕获差异。",
  "Review history was reset for the current runtime or resource session.": "当前运行时或资源会话的审阅历史已重置。",
  "Review capture capacity was reached; some changes could not be retained.": "已达到修改捕获容量上限，部分变化未能保留。",
  "Already-applied review: inspect captured changes after a task. This is not patch approval.": "审阅已应用的修改：在任务后检查捕获的变化，不是补丁审批。",
  "Review changes": "审阅修改",
  "Changes {start}–{end} of {total} · Page {page} of {pages}": "修改 {start}–{end} / {total} · 第 {page} / {pages} 页",
  "No captured changes in this live session.": "当前实时会话没有捕获的修改。",
  "Review data will load when this panel is opened.": "展开面板时加载审阅数据。",
  "Open current source": "打开当前源码",
  "View captured diff": "查看捕获的差异",
  "Source changed after capture; the current source may differ from this review.": "捕获后源码发生变化，当前源码可能与本次审阅不同。",
  "Concurrent changes overlapped this entry; attribution is not isolated.": "并发变化与此项重叠，无法独立归因。",
  "Reason: {reason}": "原因：{reason}",
  "Text difference: {diff}": "文本差异：{diff}",
  "Outcome: {status}": "结果：{status}",
  "Path unavailable": "路径不可用",
  "Unavailable": "不可用",
  "Pending": "待处理",
  "Unchanged": "无变化",
  "Ready": "就绪",
  "Observed": "观察到",
  "Preparing": "准备中",
  "Interrupted": "已中断",
  "Failed": "失败",
  "Complete": "完成",
  "Observed workspace change": "观察到的工作区变化",
  "Tool-reported · {tool}": "工具报告 · {tool}",
  "The operation was not applied": "操作未应用",
  "Review retention limit reached": "已达到审阅保留上限",
  "No before snapshot was available": "没有可用的修改前快照",
  "Source changed during capture": "捕获时源发生变化",
  "Captured source is unavailable": "捕获的源码不可用",
  "Source is too large": "源码过大",
  "Source is not text": "源不是文本",
  "Sensitive source was not captured": "敏感源码未被捕获",
  "Outside the selected project": "位于所选项目之外",
  "Preview only: diff and source opening are simulated.": "仅用于预览：差异和源码打开操作均为模拟。",
  "Review summary: {captured} captured · {reported} reported · {observed} observed · {unavailable} unavailable": "修改审阅：{captured} 项已捕获 · {reported} 项工具报告 · {observed} 项观察到 · {unavailable} 项不可用",
  "Use the runtime recovery controls below. Reloading does not clear uncertain work; no task will be replayed.": "请使用下方运行时恢复控件。重载不能清除未确认工作；不会重放任务。",
  "Runtime extensions": "运行时扩展",
  "Providers and models": "供应商与模型",
  "Default model": "默认模型",
  "Select a default model": "选择默认模型",
  "No models available": "暂无可用模型",
  "Provider": "供应商",
  "Select a provider": "选择供应商",
  "Add API key": "添加 API 密钥",
  "Update API key": "更新 API 密钥",
  "Sign in": "登录",
  "Add endpoint": "添加端点",
  "Endpoint name": "端点名称",
  "Base URL": "接口地址",
  "Model ID": "模型 ID",
  "Save endpoint": "保存端点",
  "Remove endpoint": "删除端点",
  "Remove credentials": "移除凭证",
  "No API-key providers are available yet.": "暂无支持 API 密钥的供应商。",
  "Loading providers…": "正在加载供应商…",
  "Refresh providers": "刷新供应商",
  "Refreshing providers…": "正在刷新供应商…",
  "Trusted extension code runs outside covered tool approvals; this is not a sandbox.": "受信扩展内部代码不受已覆盖工具审批约束；这不是安全沙箱。",
  "Permissions ({count})": "权限（{count}）",
  "Controlled execution: covered tools ask for approval; this is not a sandbox.": "受控执行：覆盖的工具会请求审批；这不是安全沙箱。",
  "Execution policy is unavailable. No additional permission is implied.": "执行策略不可用，不表示获得额外权限。",
  "Requested target": "请求的目标",
  "Complete command": "完整命令",
  "Target unavailable — inspect full input before deciding.": "目标不可用——请先查看完整输入再决定。",
  "Approval queue (synthetic)": "审批队列（模拟）",
  "Pending approvals": "待审批操作",
  "Pending actions ({count})": "待处理操作（{count}）",
  "Unable to send message": "无法发送消息",
  "A folder is required to send a message or add context.": "发送消息或添加上下文需要先打开文件夹。",
  "Please open a folder or workspace to continue.": "请先打开文件夹或工作区再继续。",
  "Cancel keeps this draft. Nothing is sent or attached.": "取消会保留这份草稿，不会发送或附加任何内容。",
  "Keep editing": "继续编辑",
  "Close message": "关闭提示",
  "OK": "确定",
  "Interface settings": "界面设置",
  "Language": "语言",
  "Close settings": "关闭设置",
  "For this preview only. Reloading the page restores English.": "仅用于本次预览。刷新页面后恢复英文。",
  "Candidate chat": "候选聊天",
  "Conversation navigation": "对话导航",
  "Current conversation": "当前对话",
  "Browse saved conversations": "浏览已保存的对话",
  "Chat history": "对话历史",
  "New conversation": "新建对话",
  "Conversation history": "对话历史区域",
  "Back to conversation": "返回对话",
  "Message": "消息",
  "Ask pi anything…": "向 pi 提问…",
  "Stop current task": "停止当前任务",
  "Send message": "发送消息",
  "What should we work on?": "今天想做些什么？",
  "Copy code": "复制代码",
  "Copy": "复制",
  "Code block": "代码块",
  "Clipboard unavailable — select the code to copy manually.": "剪贴板不可用，请选中代码手动复制。",
  "Copying code…": "正在复制代码…",
  "Copy timed out — clipboard completion is unknown. You can retry or copy manually.": "复制超时，无法确认剪贴板是否已写入。请重试或手动复制。",
  "Code copied.": "代码已复制。",
  "Copy failed — clipboard permission is denied or unavailable. Select the code to copy manually.": "复制失败，剪贴板权限被拒绝或不可用。请选中代码手动复制。",
  "Blocked link": "已阻止的链接",
  "(Link blocked — only absolute HTTP(S) links without credentials are available in this preview.)": "（链接已阻止，本预览仅允许不含凭据的 HTTP(S) 绝对链接。）",
  "Opening an external browser tab; native host routing is not available in this preview.": "正在打开外部浏览器标签页；本预览不支持原生宿主路由。",
  "Model not configured": "未配置模型",
  "Model and thinking level": "模型与思考强度",
  "Model": "模型",
  "Thinking level": "思考强度",
  "Applied: {model} · {thinking}": "已应用：{model} · {thinking}",
  "Applied: {thinking}": "已应用：{thinking}",
  " · Next turn (pending): {thinking}": " · 下一轮（待应用）：{thinking}",
  "thinking: {thinking}": "思考强度：{thinking}",
  "Applying next turn: {settings}": "正在应用下一轮设置：{settings}",
  "Next turn (pending): {settings}": "下一轮（待应用）：{settings}",
  "Loading model settings…": "正在加载模型设置…",
  "off": "关闭",
  "minimal": "最低",
  "low": "低",
  "medium": "中",
  "high": "高",
  "xhigh": "最高",
  "Stopping… Waiting for the task to settle.": "正在停止…等待任务结束。",
  "Replying…": "正在回复…",
  "Working…": "正在执行…",
  "Waiting for approval…": "等待审批…",
  "This request has expired.": "此请求已过期。",
  "Connecting to the preview…": "正在连接预览…",
  "Loading runtime and models…": "正在加载运行时和模型…",
  "Runtime unavailable": "运行时不可用",
  "Use Simulate recovery in the preview toolbar to try again.": "请使用预览工具栏的“模拟恢复”重试。",
  "No configured model is available. Use Simulate recovery in the preview toolbar.": "没有可用的已配置模型。请使用预览工具栏的“模拟恢复”。",
  "Synchronizing draft…": "正在同步草稿…",
  "Conversation handoff: {error}. No conversation switch was made. Retry or browse history.": "对话交接：{error}。未切换对话，请重试或浏览历史。",
  "Message activity": "消息活动",
  "Tool details": "工具详情",
  "Thinking details": "思考详情",
  "Tool": "工具",
  "Thinking": "思考",
  "Parameters / command": "参数／命令",
  "Tool input": "工具输入",
  "Not provided": "未提供",
  "Upstream thinking": "上游思考",
  "Output": "输出",
  "Tool output": "工具输出",
  "Truncated — only the bounded projection is shown.": "已截断，仅显示有界投影内容。",
  "You": "你",
  "Thinking…": "正在思考…",
  "{count} failed": "{count} 项失败",
  "{count} interrupted": "{count} 项中断",
  "{count} truncated": "{count} 项已截断",
  "Working": "执行中",
  "{count} tool": "{count} 次工具调用",
  "{count} tools": "{count} 次工具调用",
  "{count} thinking": "{count} 项思考",
  "thinking": "思考中",
  "preparing": "准备中",
  "executing": "执行中",
  "complete": "已完成",
  "failed": "失败",
  "interrupted": "已中断",
  "Saved conversations": "已保存的对话",
  "Refresh saved conversations": "刷新已保存的对话",
  "Refresh history": "刷新历史",
  "Saved conversations: {error}. Refresh or retry the handoff. No conversation switch was made.": "已保存的对话：{error}。请刷新或重试交接，未切换对话。",
  "Loading saved conversations…": "正在加载已保存的对话…",
  "No saved conversations in this project.": "此项目中没有已保存的对话。",
  "No preview available.": "暂无摘要。",
  "{excerpt}\nModified: {modified}": "{excerpt}\n修改时间：{modified}",
  "Restore {title}": "恢复 {title}",
  "untitled conversation": "未命名对话",
  "Untitled conversation": "未命名对话",
  "Saved conversation pages": "已保存对话分页",
  "Previous conversations": "上一页对话",
  "Previous page": "上一页",
  "Page {page} of {total}": "第 {page} 页，共 {total} 页",
  "Next conversations": "下一页对话",
  "Next page": "下一页",
  "Simulated session handoff": "模拟对话交接",
  "Synthetic browser preview only. Confirmation is not an ownership lock. A confirmed handoff stops the task and waits for settlement, then clears unsent drafts, attachments and temporary grants/review state. Historical extensions are not loaded automatically.": "仅为模拟浏览器预览，确认不代表独占锁。确认交接后将停止任务并等待结束，然后清除未发送草稿、附件和临时授权／审阅状态。不会自动加载历史扩展。",
  "Confirm only after leaving the original entry point. This button simulates that confirmation; no real session is accessed.": "离开原入口后再确认。此按钮仅模拟确认，不访问真实会话。",
  "Create a new simulated conversation?": "新建模拟对话？",
  "Confirm simulated handoff": "确认模拟交接",
  "Cancel": "取消",
  "Cancel simulated handoff": "取消模拟交接",
  "Simulate restore failure": "模拟恢复失败",
  "Simulate Stop failure": "模拟停止失败",
  "Retained history is unavailable. Retry when the conversation is ready.": "保留的历史不可用，请在对话就绪后重试。",
  "This retained history is no longer current. Refresh the history page.": "此保留历史已过期，请刷新历史页面。",
  "Loading retained history was cancelled. You can retry.": "已取消加载保留历史，可以重试。",
  "Restored history": "已恢复的历史",
  "One window of up to 32 retained entries is shown, most recent window first; earlier history is not shown until requested. Model context is owned by pi, not this display. Historical tool names do not mean those tools or extensions are loaded or available. Unsupported historical content is marked in the retained entries.": "每个窗口最多显示 32 条保留记录，先显示最近窗口；更早历史需按需加载。模型上下文由 pi 管理，而非此界面。历史工具名称不代表工具或扩展已加载或可用。不支持的历史内容会在保留记录中标明。",
  "Entries {start}–{end} of {total}. ": "第 {start}–{end} 条，共 {total} 条。",
  "{total} retained entries. ": "共 {total} 条保留记录。",
  "Page {page} of {total}.": "第 {page} 页，共 {total} 页。",
  "Restored history pages": "已恢复历史分页",
  "Previous / earlier": "更早历史",
  "Newer": "较新历史",
  "Loading retained history…": "正在加载保留历史…",
  "Retained history is unavailable. Restore the conversation again from Sessions.": "保留历史不可用，请从对话历史中重新恢复对话。",
  "No retained history entries are available.": "没有可用的保留历史记录。",
  "Retained history entries": "保留历史记录",
  "You (saved)": "你（已保存）",
  "Assistant / activity (saved)": "助手／活动（已保存）",
  "View retained text for entry {entry}": "查看第 {entry} 条保留原文",
  "View retained text": "查看保留原文",
  "Retained text preview unavailable for this notice.": "此提示没有可用的保留原文预览。",
  "Retained text": "保留原文",
  "Literal, immutable retained history snapshot, not the current file. Attachments reflect retained text only. Nothing here opens a file or executes historical content.": "这是不可变的历史原文快照，而非当前文件。附件只反映保留的文本；此处不会打开文件或执行历史内容。",
  "Close retained text": "关闭保留原文",
  "First chunk": "首个片段",
  "Previous chunk": "上个片段",
  "Next chunk": "下个片段",
  "Loading retained text…": "正在加载保留原文…",
  "Characters {start}–{end} of {total}. Only this chunk is held in the view.": "第 {start}–{end} 个字符，共 {total} 个。界面仅持有当前片段。",
  "Retry retained text": "重新加载保留原文",
  "Earlier chunk navigation is bounded. Use First chunk to return to the beginning.": "更早片段导航有数量上限。使用“首个片段”返回开头。",
  "Literal retained text": "保留原文内容",
  "Single folder only": "仅支持单文件夹",
  "Multiple workspace folders are not supported. Open a single local folder.": "不支持多文件夹工作区，请打开单个本地文件夹。",
  "Remote not supported": "不支持远程环境",
  "Remote extension hosts are not supported, including remote file workspaces.": "不支持远程扩展宿主，包括远程文件工作区。",
  "Local folder required": "需要本地文件夹",
  "Non-file workspaces are not supported. Open a local folder.": "不支持非文件工作区，请打开本地文件夹。",
  "No workspace folder": "没有工作区文件夹",
  "Open a local folder to start a pi session.": "打开本地文件夹以启动 pi 会话。",
  "Open folder": "打开文件夹",
  "Workspace not trusted": "工作区未受信任",
  "Grant workspace trust in VS Code before choosing pi resources.": "选择 pi 资源前，请在 VS Code 中授予工作区信任。",
  "Manage workspace trust": "管理工作区信任",
  "Choice: allow project resources. Changing restarts runtime.": "已选择允许项目资源。更改将重启运行时。",
  "Choice: continue without project resources. Changing restarts runtime.": "已选择不使用项目资源。更改将重启运行时。",
  "Not chosen yet.": "尚未选择。",
  "Project resources — {folder}": "项目资源 — {folder}",
  "Project resources": "项目资源",
  "Choose project resource consent. Controlled execution loads only the bundled approval extension; third-party extensions are disabled regardless of this choice. This is not a sandbox or tool authorization.": "请选择是否允许项目资源。受控执行仅加载内置审批扩展；无论如何选择，第三方扩展都被禁用。这不是沙箱或工具授权。",
  "Allow resources": "允许项目资源",
  "Continue without": "不使用资源并继续",
  "Allow once": "仅允许一次",
  "Allow this session": "允许本次会话",
  "Deny": "拒绝",
  "Session authorization unavailable: no reliably matchable scope. Review full input before allowing once.": "无法授予会话授权：缺少可靠匹配的范围。仅允许一次前请审阅完整输入。",
  "Exact session scope (no directory or command-prefix grant): {scope}": "精确会话范围（不授予目录或命令前缀权限）：{scope}",
  "Tool approvals": "工具审批",
  "Approval required · {tool}": "需要审批 · {tool}",
  "Full input": "完整输入",
  "Session scope": "会话范围",
  "Session grants ({count}) · inspect / revoke": "会话授权（{count}）· 查看／撤销",
  "Revoke": "撤销",
  "Conversation": "对话",
  "Loading": "加载中",
  "Streaming": "流式回复",
  "Formatted reply (synthetic)": "格式化回复（模拟）",
  "Untrusted output (synthetic)": "不可信输出（模拟）",
  "Activity before reply (synthetic)": "活动先于回复（模拟）",
  "Approval": "审批",
  "Attachment": "附件",
  "Source changed": "来源已变化",
  "Long live history": "较长实时历史",
  "Saved sessions (synthetic)": "已保存的会话（模拟）",
  "Saved sessions error (synthetic; Refresh recovers)": "会话加载错误（模拟，可刷新恢复）",
  "No saved sessions (synthetic)": "无已保存会话（模拟）",
  "Captured review (synthetic)": "捕获的审阅（模拟）",
  "Runtime error": "运行时错误",
  "No folder": "无文件夹",
  "Untrusted workspace": "未受信任工作区",
  "No model": "无模型",
  "Blocked workspace": "工作区被阻断",
  " (later slice)": "（后续切片）",
  "Synthetic host · candidate preview": "模拟宿主 · 候选预览",
  "Scenario": "场景",
  "Theme": "主题",
  "Sidebar": "侧栏",
  "Sidebar width": "侧栏宽度",
  "Dark": "深色",
  "Light": "浅色",
  "High contrast": "高对比",
  "Reset": "重置",
  "Simulate recovery": "模拟恢复",
  "Add context": "添加上下文", "Add file": "添加文件", "Draft context": "草稿上下文", "whole file": "整文件", "bytes": "字节",
  "Preview complete snapshot": "查看完整快照",
  "Preview": "预览",
  "Remove": "移除",
  "Attachment preview": "附件预览",
  "Close preview": "关闭预览",
  "Literal attachment text": "附件原文",
  "Add selection": "添加选区",
  "selection · original L{startLine}:{startCharacter}–L{endLine}:{endCharacter} (end exclusive)": "选区 · 原始 L{startLine}:{startCharacter}–L{endLine}:{endCharacter}（不含结束位置）",
  "unsaved snapshot": "未保存快照",
  "attached": "已附加",
  "changed": "来源已变化",
  "unavailable": "不可用",
  "confirmation-required": "需要确认",
  "old snapshot": "旧快照",
  "Use latest contents": "使用最新内容",
  "Use old snapshot": "使用旧快照",
  "Send checks the source and asks you to confirm the latest file.": "发送会检查来源并要求确认最新文件。",
  "Selection stays fixed. Send checks the source before confirming the old snapshot or reattaching.": "选区保持固定。发送会检查来源，然后确认旧快照或重新附加。",
  "Context delivery: {delivery}": "上下文投递：{delivery}",
  "Preparing context… Stop cancels preparation.": "正在准备上下文…停止可取消准备。",
  "Preparation cancelled. Draft retained.": "准备已取消。草稿已保留。",
  "Context operation: {code}. Review the draft before retrying.": "上下文操作：{code}。请检查草稿后再重试。",
  "Attachment history": "附件历史",
  "Retained attachment history": "保留附件历史",
  "Memory-only retained snapshots, not current files or model context. Bounded to 128 snapshots; restarting or changing resources loses this history.": "仅内存保留快照，不是当前文件或模型上下文。最多保留 128 项；重启或更改资源会丢失此历史。",
  "Loading retained attachment history…": "正在加载保留附件历史…",
  "Snapshots {start}–{end} of {total}": "快照 {start}–{end}，共 {total} 项",
  "No retained attachment submissions in this live session.": "当前会话没有保留附件提交。",
  "Attachment history pages": "附件历史分页",
  "First page": "首页",
  "Latest page": "最新页",
  "Attachment preparation failure (synthetic)": "附件准备失败（模拟）",
  "Attachment capacity rejection (synthetic)": "附件容量拒绝（模拟）",
  "Context limits and privacy": "上下文限制与隐私",
  "256 KiB per item · 20 attachments · 1 MiB total · 8000 body characters. Nonsecret workspace text only. Unsaved content is never saved automatically.": "单项 256 KiB · 最多 20 项附件 · 总计 1 MiB · 正文 8000 字符。仅添加工作区非秘密文本。未保存内容不会自动保存。",
  "Attachment delivery uncertain (synthetic)": "附件投递不确定（模拟）",
  "Remove or reattach unavailable context; reduce oversized text. For uncertain delivery, Stop or Reset before retrying. Reset loses the draft and memory-only history.": "移除或重新附加不可用上下文；缩减超限文本。投递不确定时先停止或重置，再重试。重置会丢失草稿与仅内存历史。",
  "Literal retained snapshot, not the current file. Content is never rendered as Markdown or loaded as a resource.": "这是保留的字面快照，不是当前文件。原文不会作为 Markdown 渲染或作为资源加载。",
  "Close attachment history": "关闭附件历史",
  "Simulate source edit": "模拟来源编辑",
  "Long context and literal content (synthetic)": "长上下文与字面内容（模拟）",
  "Attachment source unavailable (synthetic)": "附件来源不可用（模拟）",
  "Open a workspace text editor.": "请打开工作区文本编辑器。",
  "Select a nonempty range.": "请选择非空选区。",
  "Attach one selection at a time.": "请一次附加一个选区。",
  "Cancelled": "已取消",
  "Operation in progress": "操作进行中",
  "Draft changed; synchronized": "草稿已变化并已同步",
  "Trusted local workspace required": "需要受信任的本地工作区",
  "Attachment count limit reached (20)": "附件数量达到上限（20 项）",
  "Total attachment text exceeds 1 MiB": "附件总量超过 1 MiB",
  "Invalid context source": "上下文来源无效",
  "Source is outside the workspace": "来源不在工作区内",
  "Context source unavailable": "上下文来源不可用",
  "Text context only": "仅支持文本上下文",
  "Context source is too large": "上下文来源过大",
  "Attachment exceeds 256 KiB": "附件超过 256 KiB",
  "Attachment metadata is too large": "附件元数据过大",
  "Secret-like source blocked": "已阻止疑似秘密来源",
  "Source changed; confirm each snapshot": "来源已变化，请逐项确认快照",
  "Retained attachment history is full (128 snapshots)": "保留附件历史已满（128 个快照）",
  "Attachment message is too large": "附件消息过大",
  "Delivery uncertain; no automatic retry": "投递不确定，未自动重试",
  "Acknowledgement timed out; no automatic retry": "接纳确认超时，未自动重试",
  "Submission rejected": "提交被拒绝",
  "Runtime connection unavailable; attachment history cleared": "运行时连接不可用，附件历史已清除",
  "Admitted by host": "宿主已接纳",
  "Delivery attempted": "已尝试投递",
  "Accepted by runtime": "运行时已接纳",
  "Task pending": "任务待完成",
  "Delivery uncertain": "投递不确定",
  "Task settled": "任务已结束",
  "Task interrupted": "任务已中断",
  "Unknown delivery": "投递状态未知",
  "Open a workspace text editor and select code first.": "请先打开工作区文本编辑器并选中代码。",
  "Select a nonempty range of code first.": "请先选中一段非空代码。",
  "Select one range at a time, then attach it.": "请一次选择一个范围，然后再附加。",
  "Selection cancelled. Draft retained.": "已取消选择。草稿已保留。",
  "Wait for the current operation.": "请等待当前操作完成。",
  "Draft changed; synchronized with the host.": "草稿已变化，已与宿主同步。",
  "A trusted local workspace and ready runtime are required.": "需要受信任的本地工作区和已就绪的 runtime。",
  "At most 20 attachments. Remove an item before attaching more.": "最多 20 项附件。请先移除一项再附加。",
  "Attachment text exceeds 1 MiB. Reduce or remove attachments before sending.": "附件文本超过 1 MiB。请在发送前缩减或移除附件。",
  "Credential-like source blocked. Attach only nonsecret code.": "已阻止疑似凭据来源。请只附加不含秘密的代码。",
  "Attachment history is full. Inspect history, or use Developer: Reload Window to restart (current chat, attachment snapshots and unsent draft will be lost). Plain chat remains available.": "附件历史已满。请查看历史，或使用「开发人员: 重新加载窗口」重启（当前聊天、附件快照和未发送草稿将丢失）。普通聊天仍可用。",
  "Sources changed. Send checks all attachments; confirm each marked snapshot or remove and reattach.": "来源已变化。发送会检查所有附件；请确认每项已标记的快照，或移除后重新附加。",
  "Runtime/session ended. In-memory attachment history ended; reattach for the new session.": "Runtime／会话已结束。内存中的附件历史已结束；请为新会话重新附加。",
  "Delivery uncertain. No retry was made. Stop or restart before retrying.": "投递不确定。未进行重试。请先停止或重启，然后再试。",
  "Acknowledgement timed out. No retry was made. Stop or restart.": "接纳确认超时。未进行重试。请停止或重启。",
  "Runtime rejected this submission. Inspect history before trying again.": "Runtime 拒绝了此次提交。请先检查历史再重试。",
  "File could not be attached or sent. Remove and reattach a smaller eligible workspace text file.": "无法附加或发送该文件。请移除后重新附加更小的合格工作区文本文件。",
  "Extension interactions": "扩展交互",
  "No extension interaction is active.": "当前没有待处理的扩展交互。",
  "Select an option": "选择一个选项",
  "Choose an option…": "请选择…",
  "Your response": "你的答复",
  "Editor text": "编辑文本",
  "Type your response…": "输入答复…",
  "Response exceeds 32,768 UTF-8 bytes (32 KiB). Shorten the text and submit again, or cancel this interaction.": "答复超过 32,768 UTF-8 字节（32 KiB）。请缩短文本后重新提交，或取消此交互。",
  "Choose a response": "选择答复",
  "Yes": "是",
  "No": "否",
  "Submit response": "提交答复",
  "Cancel this interaction": "取消此交互",
  "Canceling this request may let the extension continue running. It does not stop the task.": "取消此请求后，扩展仍可能继续运行；这不会停止任务。",
  "Origin: trusted runtime extension; not authenticated.": "来源：受信运行时扩展；未经认证。",
  "Local cutoff (receipt-based; not remote expiry):": "本地截止时间（基于回执；不代表远端过期）：",
  "time unavailable": "时间不可用",
  "Custom/component TUI and arbitrary terminal layouts are not rendered. Only standard forms and bounded literal feedback are shown.": "不渲染自定义／组件 TUI 或任意终端布局。此处仅显示标准表单与有界字面反馈。",
  "Extension interaction handling is blocked. New answers are disabled; runtime work may still be running.": "扩展交互处理已阻止。答复已禁用；运行时工作仍可能继续。",
  "The host reported an interaction error. Remote completion is unknown.": "宿主报告了交互错误。远端是否完成未知。",
  "Extension feedback": "扩展反馈",
  "{count} older feedback item was omitted due to capacity.": "因容量限制，已有 {count} 条较早反馈未显示。",
  "{count} older feedback items were omitted due to capacity.": "因容量限制，已有 {count} 条较早反馈未显示。",
  "{count} interaction queued.": "有 {count} 个交互正在排队。",
  "{count} interactions queued.": "有 {count} 个交互正在排队。",
  "Repeated incoming requests exceeded the limit. New interactions are blocked; extension code may still be running.": "连续收到的请求超过上限。新交互已阻止；扩展代码仍可能运行。",
  "An interaction reply could not be confirmed. The remote result is unknown; answers are blocked.": "无法确认交互答复是否送达。远端结果未知；答复已阻止。",
  "A local cutoff timer failed. Interaction handling is blocked.": "本地截止计时器失败，交互处理已阻止。",
  "The local clock is unavailable. Interaction handling is blocked.": "本地时钟不可用，交互处理已阻止。",
  "The interaction identifier budget is exhausted. Interaction handling is blocked.": "交互标识预算已耗尽，交互处理已阻止。",
  "Notification": "通知",
  "Status": "状态",
  "Widget text": "组件文本",
  "Requested title text": "请求显示的标题文本",
  "Requested editor text": "请求显示的编辑器文本",
  "Info": "信息",
  "Warning": "警告",
  "Error": "错误",
  "Press Ctrl+Enter to submit; Enter adds a new line.": "按 Ctrl+Enter 提交；按 Enter 换行。",
  "Execution profile": "执行配置",
  "Controlled execution": "受控执行",
  "Trusted execution": "受信执行",
  "Runtime is idle.": "运行时空闲。",
  "Waiting for host confirmation before loading a trusted extension.": "正在等待宿主确认后再加载受信扩展。",
  "Changing execution profile. Controls are temporarily disabled.": "正在切换执行配置；控件暂时禁用。",
  "Runtime outcome is uncertain. Reloading or seeing no process does not clear recovery.": "运行时结果不确定。重新加载或看不到进程都不能清除恢复状态。",
  "Execution profile is not ready.": "执行配置尚未就绪。",
  "Choosing trusted confirms the enabled Settings plugin, or opens the file picker when none is enabled, then asks the host to load it.": "选择受信执行会确认已启用的设置插件；若没有启用项，则打开文件选择器，再请宿主加载。",
  "Use controlled execution": "使用受控执行",
  "Load a trusted extension…": "加载受信扩展…",
  "Covered tools ask for approval. This is not a sandbox.": "覆盖的工具会请求审批。这不是安全沙箱。",
  "Loads the enabled Settings plugin after host confirmation, or uses the file picker when none is enabled. Not a sandbox.": "经宿主确认后加载已启用的设置插件；若没有启用项则使用文件选择器。不是安全沙箱。",
  "Too many plugins are enabled. Disable extras in Settings so only one loads.": "启用的插件过多。请在设置中关闭多余项，只保留一个加载。",
  "The plugin inventory cannot be read. Trusted apply did not start.": "无法读取插件清单。未开始受信应用。",
  "Trusted extension code is not a security sandbox. Its internal code and external effects are outside covered approval; covered tools still ask for approval.": "受信扩展代码不在沙箱中；其内部代码和外部影响不受已覆盖的审批约束。已覆盖工具仍会请求审批。",
  "Each VS Code window admits its own runtime. Two windows on the same folder can change the same files at once.": "每个 VS Code 窗口各自准入一个运行时。同一文件夹上的两个窗口可能同时改文件。",
  "Ending an owned runtime may interrupt irreversible work. The host will ask for confirmation.": "结束自有运行时可能中断不可逆工作；宿主会请求确认。",
  "End owned runtime…": "结束自有运行时…",
  "Recover controlled execution": "恢复受控执行",
  "The host reported an execution-profile error. No profile change or recovery is implied.": "宿主报告了执行配置错误。不代表配置已切换或恢复已完成。",
  "Notes": "注意事项"
} satisfies Record<UiText, string>;
