import { createContext, useContext } from "react";

/** Source-language UI identifiers only; never pass host/user content through this Interface. */
export type UiText =
  | "Replay Pi logo animation"
  | "Set up this project"
  | "Use this project's pi settings and resources?"
  | "What does this choice affect?"
  | "A project session needs an explicit resource choice before it can start."
  | "Cancel keeps this draft and does not grant consent or start a runtime."
  | "Pi chat"
  | "Connecting to the extension host…"
  | "Reload the VS Code window to restart controlled execution. Unsent drafts are not persisted; copy them before reloading."
  | "No configured model is available. Open Interface settings to configure a provider API key."
  | "Open provider settings"
  | "For this view only. Reloading the view restores English."
  | "(Link blocked — only absolute HTTP(S) links without credentials are allowed.)"
  | "Opening an external link through VS Code."
  | "Task failed"
  | "Retrying…"
  | "Compacting context…"
  | "Task completed"
  | "Task stopped · Side effects are not rolled back."
  | "Preview controls"
  | "Simulate pending approvals"
  | "Simulate captured changes"
  | "Simulate review loss"
  | "Simulate extension request"
  | "Simulate runtime recovery"
  | "Review changes ({count})"
  | "Review changes pages"
  | "Review text retained: {bytes} / 8 MiB."
  | "Review data is stale; the runtime or source changed. Refresh the review before relying on it."
  | "Review data is unavailable; no captured diff can be opened for missing entries."
  | "Review history was reset for the current runtime or resource session."
  | "Review capture capacity was reached; some changes could not be retained."
  | "Already-applied review: inspect captured changes after a task. This is not patch approval."
  | "Review changes"
  | "Changes {start}–{end} of {total} · Page {page} of {pages}"
  | "No captured changes in this live session."
  | "Review data will load when this panel is opened."
  | "Open current source"
  | "View captured diff"
  | "Source changed after capture; the current source may differ from this review."
  | "Concurrent changes overlapped this entry; attribution is not isolated."
  | "Reason: {reason}"
  | "Text difference: {diff}"
  | "Outcome: {status}"
  | "Path unavailable"
  | "Unavailable"
  | "Pending"
  | "Unchanged"
  | "Ready"
  | "Observed"
  | "Preparing"
  | "Interrupted"
  | "Failed"
  | "Complete"
  | "Observed workspace change"
  | "Tool-reported · {tool}"
  | "The operation was not applied"
  | "Review retention limit reached"
  | "No before snapshot was available"
  | "Source changed during capture"
  | "Captured source is unavailable"
  | "Source is too large"
  | "Source is not text"
  | "Sensitive source was not captured"
  | "Outside the selected project"
  | "Preview only: diff and source opening are simulated."
  | "Review summary: {captured} captured · {reported} reported · {observed} observed · {unavailable} unavailable"
  | "Use the runtime recovery controls below. Reloading does not clear uncertain work; no task will be replayed."
  | "Runtime extensions"
  | "Providers and models"
  | "API keys are entered in a native password prompt. Keys are never shown in this view."
  | "Default model"
  | "Select a default model"
  | "No models available"
  | "Provider"
  | "Select a provider"
  | "Configured providers: {names}"
  | "No providers configured yet."
  | "Configured{source}"
  | "Not configured"
  | "Add API key"
  | "Update API key"
  | "Remove credentials"
  | "No API-key providers are available yet."
  | "Loading providers…"
  | "Refresh providers"
  | "Refreshing providers…"
  | "Saved default. This is not a connection test."
  | "This session: {model}"
  | "No live session model yet. The default is used when a session starts."
  | "Changing the default does not replace the current session model until the host applies it."
  | "Configured means credentials are saved, not that a connection test succeeded."
  | "Trusted extension code runs outside covered tool approvals; this is not a sandbox."
  | "Permissions ({count})"
  | "Controlled execution: covered tools ask for approval; this is not a sandbox."
  | "Execution policy is unavailable. No additional permission is implied."
  | "Requested target"
  | "Complete command"
  | "Target unavailable — inspect full input before deciding."
  | "Approval queue (synthetic)"
  | "Pending approvals"
  | "Pending actions ({count})"
  | "Unable to send message"
  | "A folder is required to send a message or add context."
  | "Please open a folder or workspace to continue."
  | "Cancel keeps this draft. Nothing is sent or attached."
  | "Keep editing"
  | "Close message"
  | "OK"
  | "Interface settings"
  | "Language"
  | "Close settings"
  | "For this preview only. Reloading the page restores English."
  | "Candidate chat"
  | "Conversation navigation"
  | "Current conversation"
  | "Browse saved conversations"
  | "Chat history"
  | "New conversation"
  | "Conversation history"
  | "Back to conversation"
  | "Message"
  | "Ask pi anything…"
  | "Stop current task"
  | "Send message"
  | "What should we work on?"
  | "Copy code"
  | "Copy"
  | "Code block"
  | "Clipboard unavailable — select the code to copy manually."
  | "Copying code…"
  | "Copy timed out — clipboard completion is unknown. You can retry or copy manually."
  | "Code copied."
  | "Copy failed — clipboard permission is denied or unavailable. Select the code to copy manually."
  | "Blocked link"
  | "(Link blocked — only absolute HTTP(S) links without credentials are available in this preview.)"
  | "Opening an external browser tab; native host routing is not available in this preview."
  | "Model not configured"
  | "Model and thinking level"
  | "Model"
  | "Thinking level"
  | "Applied: {model} · {thinking}"
  | "Applied: {thinking}"
  | " · Next turn (pending): {thinking}"
  | "thinking: {thinking}"
  | "Applying next turn: {settings}"
  | "Next turn (pending): {settings}"
  | "Loading model settings…"
  | "off"
  | "minimal"
  | "low"
  | "medium"
  | "high"
  | "xhigh"
  | "Stopping… Waiting for the task to settle."
  | "Replying…"
  | "Working…"
  | "Waiting for approval…"
  | "This request has expired."
  | "Connecting to the preview…"
  | "Loading runtime and models…"
  | "Runtime unavailable"
  | "Use Simulate recovery in the preview toolbar to try again."
  | "No configured model is available. Use Simulate recovery in the preview toolbar."
  | "Synchronizing draft…"
  | "Conversation handoff: {error}. No conversation switch was made. Retry or browse history."
  | "Message activity"
  | "Tool details"
  | "Thinking details"
  | "Tool"
  | "Thinking"
  | "Parameters / command"
  | "Tool input"
  | "Not provided"
  | "Upstream thinking"
  | "Output"
  | "Tool output"
  | "Truncated — only the bounded projection is shown."
  | "You"
  | "Thinking…"
  | "{count} failed"
  | "{count} interrupted"
  | "{count} truncated"
  | "Working"
  | "{count} tool"
  | "{count} tools"
  | "{count} thinking"
  | "thinking"
  | "preparing"
  | "executing"
  | "complete"
  | "failed"
  | "interrupted"
  | "Saved conversations"
  | "Refresh saved conversations"
  | "Refresh history"
  | "Saved conversations: {error}. Refresh or retry the handoff. No conversation switch was made."
  | "Loading saved conversations…"
  | "No saved conversations in this project."
  | "No preview available."
  | "{excerpt}\nModified: {modified}"
  | "Restore {title}"
  | "untitled conversation"
  | "Untitled conversation"
  | "Saved conversation pages"
  | "Previous conversations"
  | "Previous page"
  | "Page {page} of {total}"
  | "Next conversations"
  | "Next page"
  | "Simulated session handoff"
  | "Synthetic browser preview only. Confirmation is not an ownership lock. A confirmed handoff stops the task and waits for settlement, then clears unsent drafts, attachments and temporary grants/review state. Historical extensions are not loaded automatically."
  | "Confirm only after leaving the original entry point. This button simulates that confirmation; no real session is accessed."
  | "Create a new simulated conversation?"
  | "Confirm simulated handoff"
  | "Cancel"
  | "Cancel simulated handoff"
  | "Simulate restore failure"
  | "Simulate Stop failure"
  | "Retained history is unavailable. Retry when the conversation is ready."
  | "This retained history is no longer current. Refresh the history page."
  | "Loading retained history was cancelled. You can retry."
  | "Restored history"
  | "One window of up to 32 retained entries is shown, most recent window first; earlier history is not shown until requested. Model context is owned by pi, not this display. Historical tool names do not mean those tools or extensions are loaded or available. Unsupported historical content is marked in the retained entries."
  | "Entries {start}–{end} of {total}. "
  | "{total} retained entries. "
  | "Page {page} of {total}."
  | "Restored history pages"
  | "Previous / earlier"
  | "Newer"
  | "Loading retained history…"
  | "Retained history is unavailable. Restore the conversation again from Sessions."
  | "No retained history entries are available."
  | "Retained history entries"
  | "You (saved)"
  | "Assistant / activity (saved)"
  | "View retained text for entry {entry}"
  | "View retained text"
  | "Retained text preview unavailable for this notice."
  | "Retained text"
  | "Literal, immutable retained history snapshot, not the current file. Attachments reflect retained text only. Nothing here opens a file or executes historical content."
  | "Close retained text"
  | "First chunk"
  | "Previous chunk"
  | "Next chunk"
  | "Loading retained text…"
  | "Characters {start}–{end} of {total}. Only this chunk is held in the view."
  | "Retry retained text"
  | "Earlier chunk navigation is bounded. Use First chunk to return to the beginning."
  | "Literal retained text"
  | "Single folder only"
  | "Multiple workspace folders are not supported. Open a single local folder."
  | "Remote not supported"
  | "Remote extension hosts are not supported, including remote file workspaces."
  | "Local folder required"
  | "Non-file workspaces are not supported. Open a local folder."
  | "No workspace folder"
  | "Open a local folder to start a pi session."
  | "Open folder"
  | "Workspace not trusted"
  | "Grant workspace trust in VS Code before choosing pi resources."
  | "Manage workspace trust"
  | "Choice: allow project resources. Changing restarts runtime."
  | "Choice: continue without project resources. Changing restarts runtime."
  | "Not chosen yet."
  | "Project resources — {folder}"
  | "Project resources"
  | "Choose project resource consent. Controlled execution loads only the bundled approval extension; third-party extensions are disabled regardless of this choice. This is not a sandbox or tool authorization."
  | "Allow resources"
  | "Continue without"
  | "Allow once"
  | "Allow this session"
  | "Deny"
  | "Session authorization unavailable: no reliably matchable scope. Review full input before allowing once."
  | "Exact session scope (no directory or command-prefix grant): {scope}"
  | "Tool approvals"
  | "Approval required · {tool}"
  | "Custom extension tool. This approval covers this call only; extension-internal execution is outside this approval and built-in file safeguards."
  | "Full input"
  | "Session scope"
  | "Session grants ({count}) · inspect / revoke"
  | "Revoke"
  | "Conversation"
  | "Loading"
  | "Streaming"
  | "Formatted reply (synthetic)"
  | "Untrusted output (synthetic)"
  | "Activity before reply (synthetic)"
  | "Approval"
  | "Attachment"
  | "Source changed"
  | "Long live history"
  | "Saved sessions (synthetic)"
  | "Saved sessions error (synthetic; Refresh recovers)"
  | "No saved sessions (synthetic)"
  | "Captured review (synthetic)"
  | "Runtime error"
  | "No folder"
  | "Untrusted workspace"
  | "No model"
  | "Blocked workspace"
  | " (later slice)"
  | "Synthetic host · candidate preview"
  | "Scenario"
  | "Theme"
  | "Sidebar"
  | "Sidebar width"
  | "Dark"
  | "Light"
  | "High contrast"
  | "Reset"
  | "Simulate recovery"

  | "Add context"
  | "Add file"
  | "Draft context"
  | "whole file"
  | "bytes"
  | "Preview complete snapshot"
  | "Preview"
  | "Remove"
  | "Attachment preview"
  | "Close preview"
  | "Literal attachment text"
  | "Add selection"
  | "selection · original L{startLine}:{startCharacter}–L{endLine}:{endCharacter} (end exclusive)"
  | "unsaved snapshot"
  | "attached"
  | "changed"
  | "unavailable"
  | "confirmation-required"
  | "old snapshot"
  | "Use latest contents"
  | "Use old snapshot"
  | "Send checks the source and asks you to confirm the latest file."
  | "Selection stays fixed. Send checks the source before confirming the old snapshot or reattaching."
  | "Context delivery: {delivery}"
  | "Preparing context… Stop cancels preparation."
  | "Preparation cancelled. Draft retained."
  | "Context operation: {code}. Review the draft before retrying."
  | "Attachment history"
  | "Retained attachment history"
  | "Memory-only retained snapshots, not current files or model context. Bounded to 128 snapshots; restarting or changing resources loses this history."
  | "Loading retained attachment history…"
  | "Snapshots {start}–{end} of {total}"
  | "No retained attachment submissions in this live session."
  | "Attachment history pages"
  | "First page"
  | "Latest page"
  | "Attachment preparation failure (synthetic)"
  | "Attachment capacity rejection (synthetic)"
  | "Context limits and privacy"
  | "256 KiB per item · 20 attachments · 1 MiB total · 8000 body characters. Nonsecret workspace text only. Unsaved content is never saved automatically."
  | "Attachment delivery uncertain (synthetic)"
  | "Remove or reattach unavailable context; reduce oversized text. For uncertain delivery, Stop or Reset before retrying. Reset loses the draft and memory-only history."
  | "Literal retained snapshot, not the current file. Content is never rendered as Markdown or loaded as a resource."
  | "Close attachment history"
  | "Simulate source edit"
  | "Long context and literal content (synthetic)"
  | "Attachment source unavailable (synthetic)"
  | "Open a workspace text editor."
  | "Select a nonempty range."
  | "Attach one selection at a time."
  | "Cancelled"
  | "Operation in progress"
  | "Draft changed; synchronized"
  | "Trusted local workspace required"
  | "Attachment count limit reached (20)"
  | "Total attachment text exceeds 1 MiB"
  | "Invalid context source"
  | "Source is outside the workspace"
  | "Context source unavailable"
  | "Text context only"
  | "Context source is too large"
  | "Attachment exceeds 256 KiB"
  | "Attachment metadata is too large"
  | "Secret-like source blocked"
  | "Source changed; confirm each snapshot"
  | "Retained attachment history is full (128 snapshots)"
  | "Attachment message is too large"
  | "Delivery uncertain; no automatic retry"
  | "Acknowledgement timed out; no automatic retry"
  | "Submission rejected"
  | "Runtime connection unavailable; attachment history cleared"
  | "Admitted by host"
  | "Delivery attempted"
  | "Accepted by runtime"
  | "Task pending"
  | "Delivery uncertain"
  | "Task settled"
  | "Task interrupted"
  | "Unknown delivery";
export type UiTranslator = (message: UiText, values?: Readonly<Record<string, string | number>>) => string;
export interface UiLanguage { readonly locale: string; readonly text: UiTranslator }

export function formatUiText(message: string, values: Readonly<Record<string, string | number>> = {}): string {
  return message.replace(/\{(\w+)\}/g, (match, key: string) => Object.hasOwn(values, key) ? String(values[key]) : match);
}
export const englishUi: UiLanguage = { locale: "en", text: formatUiText };
const UiTextContext = createContext<UiLanguage>(englishUi);
export const UiTextProvider = UiTextContext.Provider;
export function useUiText(): UiLanguage { return useContext(UiTextContext); }
