import type { UiText } from "../components/index.js";

/** UI copy only. Synthetic response bodies and upstream diagnostics are intentionally not translated. */
export const chineseUi = {
  "Unable to send message": "无法发送消息",
  "Please open a folder or workspace to continue.": "请先打开文件夹或工作区再继续。",
  "Close message": "关闭提示",
  "OK": "确定",
  "Interface settings": "界面设置",
  "Language": "语言",
  "Close settings": "关闭设置",
  "For this preview only. Reloading the page restores English.": "仅用于本次预览。刷新页面后恢复英文。",
  "Candidate chat": "候选聊天",
  "Conversation navigation": "对话导航",
  "Current conversation": "当前对话",
  "Browse saved conversations": "浏览已保存的对话",
  "Chat history": "对话历史",
  "New conversation": "新建对话",
  "Conversation history": "对话历史区域",
  "Back to conversation": "返回对话",
  "Message": "消息",
  "Ask pi anything…": "向 pi 提问…",
  "Stop current task": "停止当前任务",
  "Send message": "发送消息",
  "What should we work on?": "今天想做些什么？",
  "Ask a question or describe a change.": "提出问题，或描述你想要的修改。",
  "Copy code": "复制代码",
  "Copy": "复制",
  "Code block": "代码块",
  "Clipboard unavailable — select the code to copy manually.": "剪贴板不可用，请选中代码手动复制。",
  "Copying code…": "正在复制代码…",
  "Copy timed out — clipboard completion is unknown. You can retry or copy manually.": "复制超时，无法确认剪贴板是否已写入。请重试或手动复制。",
  "Code copied.": "代码已复制。",
  "Copy failed — clipboard permission is denied or unavailable. Select the code to copy manually.": "复制失败，剪贴板权限被拒绝或不可用。请选中代码手动复制。",
  "Blocked link": "已阻止的链接",
  "(Link blocked — only absolute HTTP(S) links without credentials are available in this preview.)": "（链接已阻止，本预览仅允许不含凭据的 HTTP(S) 绝对链接。）",
  "Opening an external browser tab; native host routing is not available in this preview.": "正在打开外部浏览器标签页；本预览不支持原生宿主路由。",
  "Model not configured": "未配置模型",
  "Model and thinking level": "模型与思考强度",
  "Model": "模型",
  "Thinking level": "思考强度",
  "Applied: {model} · {thinking}": "已应用：{model} · {thinking}",
  "Applied: {thinking}": "已应用：{thinking}",
  " · Next turn (pending): {thinking}": " · 下一轮（待应用）：{thinking}",
  "thinking: {thinking}": "思考强度：{thinking}",
  "Applying next turn: {settings}": "正在应用下一轮设置：{settings}",
  "Next turn (pending): {settings}": "下一轮（待应用）：{settings}",
  "Loading model settings…": "正在加载模型设置…",
  "off": "关闭",
  "minimal": "最低",
  "low": "低",
  "medium": "中",
  "high": "高",
  "xhigh": "最高",
  "Stopping… Waiting for the task to settle.": "正在停止…等待任务结束。",
  "Replying…": "正在回复…",
  "Working…": "正在执行…",
  "Connecting to the preview…": "正在连接预览…",
  "Loading runtime and models…": "正在加载运行时和模型…",
  "Runtime unavailable": "运行时不可用",
  "Use Simulate recovery in the preview toolbar to try again.": "请使用预览工具栏的“模拟恢复”重试。",
  "No configured model is available. Use Simulate recovery in the preview toolbar.": "没有可用的已配置模型。请使用预览工具栏的“模拟恢复”。",
  "Synchronizing draft…": "正在同步草稿…",
  "Conversation handoff: {error}. No conversation switch was made. Retry or browse history.": "对话交接：{error}。未切换对话，请重试或浏览历史。",
  "No activity reported": "未报告活动",
  "Message activity": "消息活动",
  "Tool details": "工具详情",
  "Thinking details": "思考详情",
  "Tool": "工具",
  "Thinking": "思考",
  "Parameters / command": "参数／命令",
  "Tool input": "工具输入",
  "Not provided": "未提供",
  "Upstream thinking": "上游思考",
  "Output": "输出",
  "Tool output": "工具输出",
  "Truncated — only the bounded projection is shown.": "已截断，仅显示有界投影内容。",
  "You": "你",
  "Thinking…": "正在思考…",
  "{count} failed": "{count} 项失败",
  "{count} interrupted": "{count} 项中断",
  "{count} truncated": "{count} 项已截断",
  "Working": "执行中",
  "{count} tool": "{count} 次工具调用",
  "{count} tools": "{count} 次工具调用",
  "{count} thinking": "{count} 项思考",
  "thinking": "思考中",
  "preparing": "准备中",
  "executing": "执行中",
  "complete": "已完成",
  "failed": "失败",
  "interrupted": "已中断",
  "Saved conversations": "已保存的对话",
  "Refresh saved conversations": "刷新已保存的对话",
  "Refresh history": "刷新历史",
  "Saved conversations: {error}. Refresh or retry the handoff. No conversation switch was made.": "已保存的对话：{error}。请刷新或重试交接，未切换对话。",
  "Loading saved conversations…": "正在加载已保存的对话…",
  "No saved conversations in this project.": "此项目中没有已保存的对话。",
  "No preview available.": "暂无摘要。",
  "{excerpt}\nModified: {modified}": "{excerpt}\n修改时间：{modified}",
  "Restore {title}": "恢复 {title}",
  "untitled conversation": "未命名对话",
  "Untitled conversation": "未命名对话",
  "Saved conversation pages": "已保存对话分页",
  "Previous conversations": "上一页对话",
  "Previous page": "上一页",
  "Page {page} of {total}": "第 {page} 页，共 {total} 页",
  "Next conversations": "下一页对话",
  "Next page": "下一页",
  "Simulated session handoff": "模拟对话交接",
  "Synthetic browser preview only. Confirmation is not an ownership lock. A confirmed handoff stops the task and waits for settlement, then clears unsent drafts, attachments and temporary grants/review state. Historical extensions are not loaded automatically.": "仅为模拟浏览器预览，确认不代表独占锁。确认交接后将停止任务并等待结束，然后清除未发送草稿、附件和临时授权／审阅状态。不会自动加载历史扩展。",
  "Confirm only after leaving the original entry point. This button simulates that confirmation; no real session is accessed.": "离开原入口后再确认。此按钮仅模拟确认，不访问真实会话。",
  "Create a new simulated conversation?": "新建模拟对话？",
  "Confirm simulated handoff": "确认模拟交接",
  "Cancel": "取消",
  "Cancel simulated handoff": "取消模拟交接",
  "Simulate restore failure": "模拟恢复失败",
  "Simulate Stop failure": "模拟停止失败",
  "Retained history is unavailable. Retry when the conversation is ready.": "保留的历史不可用，请在对话就绪后重试。",
  "This retained history is no longer current. Refresh the history page.": "此保留历史已过期，请刷新历史页面。",
  "Loading retained history was cancelled. You can retry.": "已取消加载保留历史，可以重试。",
  "Restored history": "已恢复的历史",
  "One window of up to 32 retained entries is shown, most recent window first; earlier history is not shown until requested. Model context is owned by pi, not this display. Historical tool names do not mean those tools or extensions are loaded or available. Unsupported historical content is marked in the retained entries.": "每个窗口最多显示 32 条保留记录，先显示最近窗口；更早历史需按需加载。模型上下文由 pi 管理，而非此界面。历史工具名称不代表工具或扩展已加载或可用。不支持的历史内容会在保留记录中标明。",
  "Entries {start}–{end} of {total}. ": "第 {start}–{end} 条，共 {total} 条。",
  "{total} retained entries. ": "共 {total} 条保留记录。",
  "Page {page} of {total}.": "第 {page} 页，共 {total} 页。",
  "Restored history pages": "已恢复历史分页",
  "Previous / earlier": "更早历史",
  "Newer": "较新历史",
  "Loading retained history…": "正在加载保留历史…",
  "Retained history is unavailable. Restore the conversation again from Sessions.": "保留历史不可用，请从对话历史中重新恢复对话。",
  "No retained history entries are available.": "没有可用的保留历史记录。",
  "Retained history entries": "保留历史记录",
  "You (saved)": "你（已保存）",
  "Assistant / activity (saved)": "助手／活动（已保存）",
  "View retained text for entry {entry}": "查看第 {entry} 条保留原文",
  "View retained text": "查看保留原文",
  "Retained text preview unavailable for this notice.": "此提示没有可用的保留原文预览。",
  "Retained text": "保留原文",
  "Literal, immutable retained history snapshot, not the current file. Attachments reflect retained text only. Nothing here opens a file or executes historical content.": "这是不可变的历史原文快照，而非当前文件。附件只反映保留的文本；此处不会打开文件或执行历史内容。",
  "Close retained text": "关闭保留原文",
  "First chunk": "首个片段",
  "Previous chunk": "上个片段",
  "Next chunk": "下个片段",
  "Loading retained text…": "正在加载保留原文…",
  "Characters {start}–{end} of {total}. Only this chunk is held in the view.": "第 {start}–{end} 个字符，共 {total} 个。界面仅持有当前片段。",
  "Retry retained text": "重新加载保留原文",
  "Earlier chunk navigation is bounded. Use First chunk to return to the beginning.": "更早片段导航有数量上限。使用“首个片段”返回开头。",
  "Literal retained text": "保留原文内容",
  "Single folder only": "仅支持单文件夹",
  "Multiple workspace folders are not supported. Open a single local folder.": "不支持多文件夹工作区，请打开单个本地文件夹。",
  "Remote not supported": "不支持远程环境",
  "Remote extension hosts are not supported, including remote file workspaces.": "不支持远程扩展宿主，包括远程文件工作区。",
  "Local folder required": "需要本地文件夹",
  "Non-file workspaces are not supported. Open a local folder.": "不支持非文件工作区，请打开本地文件夹。",
  "No workspace folder": "没有工作区文件夹",
  "Open a local folder to start a pi session.": "打开本地文件夹以启动 pi 会话。",
  "Open folder": "打开文件夹",
  "Workspace not trusted": "工作区未受信任",
  "Grant workspace trust in VS Code before choosing pi resources.": "选择 pi 资源前，请在 VS Code 中授予工作区信任。",
  "Manage workspace trust": "管理工作区信任",
  "Choice: allow project resources. Changing restarts runtime.": "已选择允许项目资源。更改将重启运行时。",
  "Choice: continue without project resources. Changing restarts runtime.": "已选择不使用项目资源。更改将重启运行时。",
  "Not chosen yet.": "尚未选择。",
  "Project resources — {folder}": "项目资源 — {folder}",
  "Project resources": "项目资源",
  "Choose project resource consent. Controlled execution loads only the bundled approval extension; third-party extensions are disabled regardless of this choice. This is not a sandbox or tool authorization.": "请选择是否允许项目资源。受控执行仅加载内置审批扩展；无论如何选择，第三方扩展都被禁用。这不是沙箱或工具授权。",
  "Allow resources": "允许项目资源",
  "Continue without": "不使用资源并继续",
  "Allow once": "仅允许一次",
  "Allow this session": "允许本次会话",
  "Deny": "拒绝",
  "Session authorization unavailable: no reliably matchable scope. Review full input before allowing once.": "无法授予会话授权：缺少可靠匹配的范围。仅允许一次前请审阅完整输入。",
  "Exact session scope (no directory or command-prefix grant): {scope}": "精确会话范围（不授予目录或命令前缀权限）：{scope}",
  "Tool approvals": "工具审批",
  "Approval required · {tool}": "需要审批 · {tool}",
  "Full input": "完整输入",
  "Session scope": "会话范围",
  "Session grants ({count}) · inspect / revoke": "会话授权（{count}）· 查看／撤销",
  "Revoke": "撤销",
  "Conversation": "对话",
  "Loading": "加载中",
  "Streaming": "流式回复",
  "Formatted reply (synthetic)": "格式化回复（模拟）",
  "Untrusted output (synthetic)": "不可信输出（模拟）",
  "Activity before reply (synthetic)": "活动先于回复（模拟）",
  "Approval": "审批",
  "Attachment": "附件",
  "Source changed": "来源已变化",
  "Long live history": "较长实时历史",
  "Saved sessions (synthetic)": "已保存的会话（模拟）",
  "Saved sessions error (synthetic; Refresh recovers)": "会话加载错误（模拟，可刷新恢复）",
  "No saved sessions (synthetic)": "无已保存会话（模拟）",
  "Captured review (synthetic)": "捕获的审阅（模拟）",
  "Runtime error": "运行时错误",
  "No folder": "无文件夹",
  "Untrusted workspace": "未受信任工作区",
  "No model": "无模型",
  "Blocked workspace": "工作区被阻断",
  " (later slice)": "（后续切片）",
  "Synthetic host · candidate preview": "模拟宿主 · 候选预览",
  "Scenario": "场景",
  "Theme": "主题",
  "Sidebar": "侧栏",
  "Sidebar width": "侧栏宽度",
  "Dark": "深色",
  "Light": "浅色",
  "High contrast": "高对比",
  "Reset": "重置",
  "Simulate recovery": "模拟恢复",
  "Add context": "添加上下文", "Add file": "添加文件", "Draft context": "草稿上下文", "whole file": "整文件", "bytes": "字节",
  "Preview complete snapshot": "查看完整快照",
  "Preview": "预览",
  "Remove": "移除",
  "Attachment preview": "附件预览",
  "Close preview": "关闭预览",
  "Literal attachment text": "附件原文",
  "Add selection": "添加选区",
  "selection · original L{startLine}:{startCharacter}–L{endLine}:{endCharacter} (end exclusive)": "选区 · 原始 L{startLine}:{startCharacter}–L{endLine}:{endCharacter}（不含结束位置）",
  "unsaved snapshot": "未保存快照",
  "attached": "已附加",
  "changed": "来源已变化",
  "unavailable": "不可用",
  "confirmation-required": "需要确认",
  "old snapshot": "旧快照",
  "Use latest contents": "使用最新内容",
  "Use old snapshot": "使用旧快照",
  "Send checks the source and asks you to confirm the latest file.": "发送会检查来源并要求确认最新文件。",
  "Selection stays fixed. Send checks the source before confirming the old snapshot or reattaching.": "选区保持固定。发送会检查来源，然后确认旧快照或重新附加。",
  "Context delivery: {delivery}": "上下文投递：{delivery}",
  "Preparing context… Stop cancels preparation.": "正在准备上下文…停止可取消准备。",
  "Preparation cancelled. Draft retained.": "准备已取消。草稿已保留。",
  "Context operation: {code}. Review the draft before retrying.": "上下文操作：{code}。请检查草稿后再重试。",
  "Attachment history": "附件历史",
  "Retained attachment history": "保留附件历史",
  "Memory-only retained snapshots, not current files or model context. Bounded to 128 snapshots; restarting or changing resources loses this history.": "仅内存保留快照，不是当前文件或模型上下文。最多保留 128 项；重启或更改资源会丢失此历史。",
  "Loading retained attachment history…": "正在加载保留附件历史…",
  "Snapshots {start}–{end} of {total}": "快照 {start}–{end}，共 {total} 项",
  "No retained attachment submissions in this live session.": "当前会话没有保留附件提交。",
  "Attachment history pages": "附件历史分页",
  "First page": "首页",
  "Latest page": "最新页",
  "Attachment preparation failure (synthetic)": "附件准备失败（模拟）",
  "Attachment capacity rejection (synthetic)": "附件容量拒绝（模拟）",
  "Context limits and privacy": "上下文限制与隐私",
  "256 KiB per item · 20 attachments · 1 MiB total · 8000 body characters. Nonsecret workspace text only. Unsaved content is never saved automatically.": "单项 256 KiB · 最多 20 项附件 · 总计 1 MiB · 正文 8000 字符。仅添加工作区非秘密文本。未保存内容不会自动保存。",
  "Attachment delivery uncertain (synthetic)": "附件投递不确定（模拟）",
  "Remove or reattach unavailable context; reduce oversized text. For uncertain delivery, Stop or Reset before retrying. Reset loses the draft and memory-only history.": "移除或重新附加不可用上下文；缩减超限文本。投递不确定时先停止或重置，再重试。重置会丢失草稿与仅内存历史。",
  "Literal retained snapshot, not the current file. Content is never rendered as Markdown or loaded as a resource.": "这是保留的字面快照，不是当前文件。原文不会作为 Markdown 渲染或作为资源加载。",
  "Close attachment history": "关闭附件历史",
  "Simulate source edit": "模拟来源编辑",
  "Long context and literal content (synthetic)": "长上下文与字面内容（模拟）",
  "Attachment source unavailable (synthetic)": "附件来源不可用（模拟）",
  "Open a workspace text editor.": "请打开工作区文本编辑器。",
  "Select a nonempty range.": "请选择非空选区。",
  "Attach one selection at a time.": "请一次附加一个选区。",
  "Cancelled": "已取消",
  "Operation in progress": "操作进行中",
  "Draft changed; synchronized": "草稿已变化并已同步",
  "Trusted local workspace required": "需要受信任的本地工作区",
  "Attachment count limit reached (20)": "附件数量达到上限（20 项）",
  "Total attachment text exceeds 1 MiB": "附件总量超过 1 MiB",
  "Invalid context source": "上下文来源无效",
  "Source is outside the workspace": "来源不在工作区内",
  "Context source unavailable": "上下文来源不可用",
  "Text context only": "仅支持文本上下文",
  "Context source is too large": "上下文来源过大",
  "Attachment exceeds 256 KiB": "附件超过 256 KiB",
  "Attachment metadata is too large": "附件元数据过大",
  "Secret-like source blocked": "已阻止疑似秘密来源",
  "Source changed; confirm each snapshot": "来源已变化，请逐项确认快照",
  "Retained attachment history is full (128 snapshots)": "保留附件历史已满（128 个快照）",
  "Attachment message is too large": "附件消息过大",
  "Delivery uncertain; no automatic retry": "投递不确定，未自动重试",
  "Acknowledgement timed out; no automatic retry": "接纳确认超时，未自动重试",
  "Submission rejected": "提交被拒绝",
  "Runtime ended; attachment history lost": "运行时已结束，附件历史已丢失",
  "Admitted by host": "宿主已接纳",
  "Delivery attempted": "已尝试投递",
  "Accepted by runtime": "运行时已接纳",
  "Task pending": "任务待完成",
  "Delivery uncertain": "投递不确定",
  "Task settled": "任务已结束",
  "Task interrupted": "任务已中断",
  "Task failed": "任务失败",
  "Unknown delivery": "投递状态未知"
} satisfies Record<UiText, string>;
